using IntoTheSpireverse.IntoTheSpireverseCode.Compatibility;

namespace IntoTheSpireverse.IntoTheSpireverseCode.Character;

public abstract class IntoTheSpireversePower : CustomPowerModelCompatibility;